version: '3.4'

services:
  redis:
    image: redis:6.0.15
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  app:
    build:
      context: "."
      target: web
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app:create_app()
      - FLASK_DEBUG=1
      - BROKER_URL=redis://redis:6379/0
      - BACKEND_URL=redis://redis:6379/0
      - OAUTHLIB_INSECURE_TRANSPORT=1

    entrypoint: poetry run flask run -h 0.0.0.0

    volumes:
      - ./tests:/tests


  worker:
    build:
      context: "."
      target: worker

    environment:
      - FLASK_ENV=development
      - BROKER_URL=redis://redis:6379/0
      - BACKEND_URL=redis://redis:6379/0
      - ITERATIONS=2
    depends_on:
      - app
      - redis
